name: vscode-binder
channels:
  - conda-forge
dependencies:
  - numpy
  - python-build
  - jupyter-server-proxy
  - nodejs
  - quarto
  - sphinx
  - python-dotenv
  - code-server
  - pip:
      - sphinx-revealjs
      - esbonio
      - sphinx-autobuild
      - notebook-intelligence
