---
services:
  code-server:
    build:
      context: .
      dockerfile: Dockerfile.code-server
      args:
        QUARTO_VERSION: ${QUARTO_VERSION:-1.8.26}
    image: code-server:custom
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - .config:/config
      - ${HOME}/.ssh:/config/.ssh:ro
      - ../:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped

